service: rcs
app: untie
org: seanarwa

provider:
  name: aws
  runtime: python3.7
  cfnRole: arn:aws:iam::689668396068:role/Untie-Serverless-Role
  environment:
    NAME: Restaurant Caching Service
    VERSION: 1

functions:
  root:
    handler: handler.root
    events:
      - http:
          path: /rcs
          method: get
          cors: true
